services:
  app:
    build: 
      context: .
      dockerfile: build/Dockerfile 
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - HOST_PROC=/host_proc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./tmp:/home/andres1m/go-projects/kursach/tmp
      - ./mock:/home/andres1m/go-projects/kursach/mock
      - /proc:/host_proc:ro
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  pinn-admin:
    build:
      context: ../../front/ # Путь к папке с фронтендом
      args:
        # Важно: указываем внутренний адрес бэкенда в сети Docker
        - NEXT_PUBLIC_API_URL=http://app:8080
        - NEXT_PUBLIC_API_TOKEN=pinn_secret
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  pgdata:
  minio_data: