// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateModel(ctx context.Context, arg CreateModelParams) (Model, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteModel(ctx context.Context, id string) error
	DeleteTask(ctx context.Context, id pgtype.UUID) error
	ExistsModelByID(ctx context.Context, id string) (bool, error)
	FindCachedTask(ctx context.Context, signature string) (pgtype.Text, error)
	GetActiveTasks(ctx context.Context) ([]Task, error)
	GetModelByID(ctx context.Context, id string) (Model, error)
	GetNextQueuedTask(ctx context.Context) (Task, error)
	GetRunningTasksContainers(ctx context.Context) ([]Task, error)
	GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error)
	GetTasksCount(ctx context.Context) (int64, error)
	GetTasksPaginated(ctx context.Context, arg GetTasksPaginatedParams) ([]Task, error)
	GetUpcomingScheduledTasks(ctx context.Context, scheduledAt pgtype.Timestamptz) ([]Task, error)
	ListModels(ctx context.Context) ([]Model, error)
	MarkTaskCompleted(ctx context.Context, arg MarkTaskCompletedParams) (Task, error)
	MarkTaskFailed(ctx context.Context, arg MarkTaskFailedParams) (Task, error)
	MarkTaskInitializing(ctx context.Context, id pgtype.UUID) (Task, error)
	MarkTaskQueued(ctx context.Context, id pgtype.UUID) (Task, error)
	MarkTaskRunning(ctx context.Context, arg MarkTaskRunningParams) (Task, error)
	MarkTaskScheduled(ctx context.Context, arg MarkTaskScheduledParams) (Task, error)
	MarkTaskStopped(ctx context.Context, id pgtype.UUID) (Task, error)
	UpdateModel(ctx context.Context, arg UpdateModelParams) error
}

var _ Querier = (*Queries)(nil)
