// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id, model_id, input_filename, signature, status, scheduled_at, container_image, container_envs, container_cmd, error_log, mem_lim, cpu_lim, gpu_enable
) VALUES (
    $1, $2, $3, $4, $13::task_status, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable
`

type CreateTaskParams struct {
	ID             pgtype.UUID
	ModelID        string
	InputFilename  string
	Signature      string
	ScheduledAt    pgtype.Timestamptz
	ContainerImage pgtype.Text
	ContainerEnvs  []string
	ContainerCmd   []string
	ErrorLog       pgtype.Text
	MemLim         pgtype.Int4
	CpuLim         pgtype.Int4
	GpuEnable      pgtype.Bool
	Status         TaskStatus
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.ModelID,
		arg.InputFilename,
		arg.Signature,
		arg.ScheduledAt,
		arg.ContainerImage,
		arg.ContainerEnvs,
		arg.ContainerCmd,
		arg.ErrorLog,
		arg.MemLim,
		arg.CpuLim,
		arg.GpuEnable,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
	)
	return i, err
}

const findCachedTask = `-- name: FindCachedTask :one
SELECT result_path FROM tasks
WHERE signature = $1 AND status = 'completed'
LIMIT 1
`

func (q *Queries) FindCachedTask(ctx context.Context, signature string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, findCachedTask, signature)
	var result_path pgtype.Text
	err := row.Scan(&result_path)
	return result_path, err
}

const getNextQueuedTask = `-- name: GetNextQueuedTask :one
UPDATE tasks
SET status = 'running', updated_at = NOW()
WHERE id = (
    SELECT id
    FROM tasks
    WHERE status = 'queued'
    AND (scheduled_at IS NULL OR scheduled_at <= NOW())
    ORDER BY scheduled_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
)
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable
`

func (q *Queries) GetNextQueuedTask(ctx context.Context) (Task, error) {
	row := q.db.QueryRow(ctx, getNextQueuedTask)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
	)
	return i, err
}

const getRunningTasksContainers = `-- name: GetRunningTasksContainers :many
SELECT id, container_id FROM tasks
WHERE status = 'running' AND container_id IS NOT NULL
`

type GetRunningTasksContainersRow struct {
	ID          pgtype.UUID
	ContainerID pgtype.Text
}

func (q *Queries) GetRunningTasksContainers(ctx context.Context) ([]GetRunningTasksContainersRow, error) {
	rows, err := q.db.Query(ctx, getRunningTasksContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRunningTasksContainersRow
	for rows.Next() {
		var i GetRunningTasksContainersRow
		if err := rows.Scan(&i.ID, &i.ContainerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
	)
	return i, err
}

const markTaskCompleted = `-- name: MarkTaskCompleted :one
UPDATE tasks
SET 
    status = 'completed',
    result_path = $2,
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable
`

type MarkTaskCompletedParams struct {
	ID         pgtype.UUID
	ResultPath pgtype.Text
}

func (q *Queries) MarkTaskCompleted(ctx context.Context, arg MarkTaskCompletedParams) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskCompleted, arg.ID, arg.ResultPath)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
	)
	return i, err
}

const markTaskFailed = `-- name: MarkTaskFailed :one
UPDATE tasks
SET 
    status = 'failed',
    error_log = $2,
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable
`

type MarkTaskFailedParams struct {
	ID       pgtype.UUID
	ErrorLog pgtype.Text
}

func (q *Queries) MarkTaskFailed(ctx context.Context, arg MarkTaskFailedParams) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskFailed, arg.ID, arg.ErrorLog)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
	)
	return i, err
}

const markTaskInitializing = `-- name: MarkTaskInitializing :one
UPDATE tasks
SET 
    status = 'initializing',
    updated_at = NOW()
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable
`

func (q *Queries) MarkTaskInitializing(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskInitializing, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
	)
	return i, err
}

const markTaskQueued = `-- name: MarkTaskQueued :one
UPDATE tasks
SET 
    status = 'queued',
    updated_at = NOW()
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable
`

func (q *Queries) MarkTaskQueued(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskQueued, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
	)
	return i, err
}

const markTaskRunning = `-- name: MarkTaskRunning :one
UPDATE tasks
SET 
    status = 'running',
    container_id = $2,
    started_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable
`

type MarkTaskRunningParams struct {
	ID          pgtype.UUID
	ContainerID pgtype.Text
}

func (q *Queries) MarkTaskRunning(ctx context.Context, arg MarkTaskRunningParams) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskRunning, arg.ID, arg.ContainerID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
	)
	return i, err
}

const markTaskScheduled = `-- name: MarkTaskScheduled :one
UPDATE tasks
SET 
    status = 'scheduled',
    updated_at = NOW(),
    scheduled_at = $2
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable
`

type MarkTaskScheduledParams struct {
	ID          pgtype.UUID
	ScheduledAt pgtype.Timestamptz
}

func (q *Queries) MarkTaskScheduled(ctx context.Context, arg MarkTaskScheduledParams) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskScheduled, arg.ID, arg.ScheduledAt)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
	)
	return i, err
}
