// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModel = `-- name: CreateModel :one
INSERT INTO models (id, container_image) VALUES ($1, $2) RETURNING id, container_image, created_at, updated_at
`

type CreateModelParams struct {
	ID             string
	ContainerImage string
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, createModel, arg.ID, arg.ContainerImage)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ContainerImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id, model_id, input_filename, signature, status, scheduled_at,
     container_image, container_envs, container_cmd, error_log, mem_lim,
      cpu_lim, gpu_enable, result_path, timeout_sec
) VALUES (
    $1, $2, $3, $4, $15::task_status, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec
`

type CreateTaskParams struct {
	ID             pgtype.UUID
	ModelID        string
	InputFilename  string
	Signature      string
	ScheduledAt    pgtype.Timestamptz
	ContainerImage pgtype.Text
	ContainerEnvs  []string
	ContainerCmd   []string
	ErrorLog       pgtype.Text
	MemLim         pgtype.Int4
	CpuLim         pgtype.Int4
	GpuEnable      pgtype.Bool
	ResultPath     pgtype.Text
	TimeoutSec     int32
	Status         TaskStatus
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.ModelID,
		arg.InputFilename,
		arg.Signature,
		arg.ScheduledAt,
		arg.ContainerImage,
		arg.ContainerEnvs,
		arg.ContainerCmd,
		arg.ErrorLog,
		arg.MemLim,
		arg.CpuLim,
		arg.GpuEnable,
		arg.ResultPath,
		arg.TimeoutSec,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
		&i.TimeoutSec,
	)
	return i, err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM models WHERE id = $1
`

func (q *Queries) DeleteModel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteModel, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const existsModelByID = `-- name: ExistsModelByID :one
SELECT EXISTS(SELECT 1 FROM models WHERE id = $1)
`

func (q *Queries) ExistsModelByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, existsModelByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findCachedTask = `-- name: FindCachedTask :one
SELECT result_path FROM tasks
WHERE signature = $1
    AND status = 'completed'::task_status
    AND result_path IS NOT NULL
    AND result_path != ''
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) FindCachedTask(ctx context.Context, signature string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, findCachedTask, signature)
	var result_path pgtype.Text
	err := row.Scan(&result_path)
	return result_path, err
}

const getActiveTasks = `-- name: GetActiveTasks :many
SELECT id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec FROM tasks
WHERE status = 'running' 
    OR status = 'scheduled' 
    OR status = 'queued' 
    OR status = 'initializing'
`

func (q *Queries) GetActiveTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getActiveTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.InputFilename,
			&i.ResultPath,
			&i.Signature,
			&i.Status,
			&i.ContainerID,
			&i.ContainerImage,
			&i.ContainerEnvs,
			&i.ContainerCmd,
			&i.ErrorLog,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemLim,
			&i.CpuLim,
			&i.GpuEnable,
			&i.TimeoutSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelByID = `-- name: GetModelByID :one
SELECT id, container_image, created_at, updated_at FROM models WHERE id = $1 LIMIT 1
`

func (q *Queries) GetModelByID(ctx context.Context, id string) (Model, error) {
	row := q.db.QueryRow(ctx, getModelByID, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ContainerImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextQueuedTask = `-- name: GetNextQueuedTask :one
UPDATE tasks
SET status = 'running', updated_at = NOW()
WHERE id = (
    SELECT id
    FROM tasks
    WHERE status = 'queued'
    AND (scheduled_at IS NULL OR scheduled_at <= NOW())
    ORDER BY scheduled_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
)
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec
`

func (q *Queries) GetNextQueuedTask(ctx context.Context) (Task, error) {
	row := q.db.QueryRow(ctx, getNextQueuedTask)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
		&i.TimeoutSec,
	)
	return i, err
}

const getRunningTasksContainers = `-- name: GetRunningTasksContainers :many
SELECT id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec FROM tasks
WHERE status = 'running' AND container_id IS NOT NULL
`

func (q *Queries) GetRunningTasksContainers(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getRunningTasksContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.InputFilename,
			&i.ResultPath,
			&i.Signature,
			&i.Status,
			&i.ContainerID,
			&i.ContainerImage,
			&i.ContainerEnvs,
			&i.ContainerCmd,
			&i.ErrorLog,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemLim,
			&i.CpuLim,
			&i.GpuEnable,
			&i.TimeoutSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
		&i.TimeoutSec,
	)
	return i, err
}

const getTasksCount = `-- name: GetTasksCount :one
SELECT COUNT(*) FROM tasks
`

func (q *Queries) GetTasksCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTasksCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTasksPaginated = `-- name: GetTasksPaginated :many
SELECT id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec FROM tasks
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetTasksPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetTasksPaginated(ctx context.Context, arg GetTasksPaginatedParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.InputFilename,
			&i.ResultPath,
			&i.Signature,
			&i.Status,
			&i.ContainerID,
			&i.ContainerImage,
			&i.ContainerEnvs,
			&i.ContainerCmd,
			&i.ErrorLog,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemLim,
			&i.CpuLim,
			&i.GpuEnable,
			&i.TimeoutSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingScheduledTasks = `-- name: GetUpcomingScheduledTasks :many
SELECT id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec FROM tasks
WHERE status = 'scheduled'
AND scheduled_at <= $1
ORDER BY scheduled_at ASC
`

func (q *Queries) GetUpcomingScheduledTasks(ctx context.Context, scheduledAt pgtype.Timestamptz) ([]Task, error) {
	rows, err := q.db.Query(ctx, getUpcomingScheduledTasks, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.InputFilename,
			&i.ResultPath,
			&i.Signature,
			&i.Status,
			&i.ContainerID,
			&i.ContainerImage,
			&i.ContainerEnvs,
			&i.ContainerCmd,
			&i.ErrorLog,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemLim,
			&i.CpuLim,
			&i.GpuEnable,
			&i.TimeoutSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, container_image, created_at, updated_at FROM models ORDER BY id
`

func (q *Queries) ListModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ContainerImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskCompleted = `-- name: MarkTaskCompleted :one
UPDATE tasks
SET 
    status = 'completed',
    result_path = $2,
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec
`

type MarkTaskCompletedParams struct {
	ID         pgtype.UUID
	ResultPath pgtype.Text
}

func (q *Queries) MarkTaskCompleted(ctx context.Context, arg MarkTaskCompletedParams) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskCompleted, arg.ID, arg.ResultPath)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
		&i.TimeoutSec,
	)
	return i, err
}

const markTaskFailed = `-- name: MarkTaskFailed :one
UPDATE tasks
SET 
    status = 'failed',
    error_log = $2,
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status != 'stopped'
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec
`

type MarkTaskFailedParams struct {
	ID       pgtype.UUID
	ErrorLog pgtype.Text
}

func (q *Queries) MarkTaskFailed(ctx context.Context, arg MarkTaskFailedParams) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskFailed, arg.ID, arg.ErrorLog)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
		&i.TimeoutSec,
	)
	return i, err
}

const markTaskInitializing = `-- name: MarkTaskInitializing :one
UPDATE tasks
SET 
    status = 'initializing',
    updated_at = NOW()
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec
`

func (q *Queries) MarkTaskInitializing(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskInitializing, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
		&i.TimeoutSec,
	)
	return i, err
}

const markTaskQueued = `-- name: MarkTaskQueued :one
UPDATE tasks
SET 
    status = 'queued',
    updated_at = NOW()
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec
`

func (q *Queries) MarkTaskQueued(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskQueued, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
		&i.TimeoutSec,
	)
	return i, err
}

const markTaskRunning = `-- name: MarkTaskRunning :one
UPDATE tasks
SET 
    status = 'running',
    container_id = $2,
    started_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec
`

type MarkTaskRunningParams struct {
	ID          pgtype.UUID
	ContainerID pgtype.Text
}

func (q *Queries) MarkTaskRunning(ctx context.Context, arg MarkTaskRunningParams) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskRunning, arg.ID, arg.ContainerID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
		&i.TimeoutSec,
	)
	return i, err
}

const markTaskScheduled = `-- name: MarkTaskScheduled :one
UPDATE tasks
SET 
    status = 'scheduled',
    updated_at = NOW(),
    scheduled_at = $2
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec
`

type MarkTaskScheduledParams struct {
	ID          pgtype.UUID
	ScheduledAt pgtype.Timestamptz
}

func (q *Queries) MarkTaskScheduled(ctx context.Context, arg MarkTaskScheduledParams) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskScheduled, arg.ID, arg.ScheduledAt)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
		&i.TimeoutSec,
	)
	return i, err
}

const markTaskStopped = `-- name: MarkTaskStopped :one
UPDATE tasks
SET 
    status = 'stopped',
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, model_id, input_filename, result_path, signature, status, container_id, container_image, container_envs, container_cmd, error_log, scheduled_at, started_at, finished_at, created_at, updated_at, mem_lim, cpu_lim, gpu_enable, timeout_sec
`

func (q *Queries) MarkTaskStopped(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskStopped, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputFilename,
		&i.ResultPath,
		&i.Signature,
		&i.Status,
		&i.ContainerID,
		&i.ContainerImage,
		&i.ContainerEnvs,
		&i.ContainerCmd,
		&i.ErrorLog,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemLim,
		&i.CpuLim,
		&i.GpuEnable,
		&i.TimeoutSec,
	)
	return i, err
}

const updateModel = `-- name: UpdateModel :exec
UPDATE models
SET
    container_image = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateModelParams struct {
	ID             string
	ContainerImage string
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) error {
	_, err := q.db.Exec(ctx, updateModel, arg.ID, arg.ContainerImage)
	return err
}
